import type { Candidate, PlanResult } from '../types';
import { formatTime, formatDuration } from '../engine';
import { esc, icon, primary, button, safety, t } from './html';
import { badges, budget, connectionRow, fallback, shortStop, trainName } from './common';
import { integratedRoute, routeNotes } from './route';
export function resultsScreen(result: PlanResult, dismissed: boolean): string {
  const c = dismissed ? undefined : result.recommended;
  const opportunity = result.opportunity;
  const directive = opportunity?.kind === 'ride-past' ? 'Get off early at' : opportunity?.kind === 'walk' ? 'Get off at' : 'Start at';
  const regularStop = opportunity?.kind === 'ride-past' ? shortStop(opportunity.feeder?.arrival.station.name ?? '') : '';
  const spare = c ? Math.max(0, c.haveS - c.sprintS - c.marginS) : 0;
  const timing = c ? `<div class="offer-timing"><p class="offer-spare"><strong>${formatDuration(spare)}</strong> to spare</p>${budget(c)}</div>` : '';
  const reason = ({ 'no-shortcut': 'No sprint shortcut on this trip yet. Your regular connections are below.', 'no-connections': 'No connections found. Try a different stop or departure time.', 'no-earlier-train': 'No earlier arrival found for this trip.', 'passed-stop': 'You have passed the shortcut stop. Keep your regular connection.', 'hack-inactive': 'This shortcut is currently unavailable. Follow the regular transfer.', 'missed-by': 'The sprint would not leave enough time for the full margin.', 'candidate-lookup-failed': 'We could not check the sprint route. Use your regular connection.', stale: 'Refresh the timetable before choosing a sprint route.' } as Record<string, string>)[result.reason] ?? result.reason;
  return `<section class="screen results-screen" data-screen="results" data-testid="screen"><div class="trip-title"><p class="eyebrow">${esc(result.connections[0]?.from.station.name ?? result.query.from)} →</p><h1>${esc(result.connections[0]?.to.station.name ?? result.query.to)}</h1></div>
    ${result.error ? `<p class="notice" role="status" data-testid="error">${esc(result.error)}</p>` : ''}
    ${c ? `<article class="offer-card integrated-offer" data-testid="offer-card"><div class="offer-label">${icon('run')} Sprint route</div><h2 class="offer-directive">${directive} <span>${esc(shortStop(opportunity!.hack.alight.name))}</span></h2>${regularStop ? `<p class="offer-regular-stop">Before ${esc(regularStop)}</p>` : ''}<p class="offer-service"><span class="service-name">${esc(trainName(c))}</span> · <span class="departure-time">${t(formatTime(c.departureTs))}</span> · <strong>Platform ${esc(c.platform)}</strong></p><p class="offer-arrival">Arrive ${t(formatTime(c.arrivalTs))} · <strong>${Math.round(c.gainS / 60)} min earlier</strong></p>${integratedRoute(opportunity!.hack, c, timing)}<p class="walking">${c.walkS + c.marginS <= c.haveS ? 'Walking would also make it.' : `Walking needs ${formatDuration(c.walkS)} plus margin.`}</p>${badges(result, c)}${routeNotes(opportunity!.hack, c)}${safety}</article>` : `<div class="no-offer"><span class="round-icon">${icon('train')}</span><h2>${result.opportunity?.feeder ? 'Stay aboard.' : 'Your regular connection.'}</h2><p>${esc(dismissed ? 'Your regular connections are below.' : reason || 'No sprint route on this trip yet. Your regular connections are below.')}</p></div>`}
    ${fallback(result, true)}<div class="section-heading"><h2>Regular connections</h2>${button(icon('clock'), 'refresh', 'icon-button', 'aria-label="Refresh connections"')}</div>${result.connections.map(connectionRow).join('')}
    <p class="api-credit">Timetable via transport.opendata.ch · Check tickets with SBB.</p>${c ? `${button('New search', 'plan', 'text-button')}<div class="bottom-actions results-actions">${button('Not now', 'dismiss', 'text-button')}${primary('Go live', 'live')}</div>` : `<div class="bottom-actions inline-bottom">${button(`New search ${icon('arrow')}`, 'plan', 'secondary')}</div>`}</section>`;
}
export function doneScreen(result: PlanResult, selected?: Candidate): string {
  const c = selected ?? result.recommended;
  return `<section class="screen done-screen" data-screen="done" data-testid="screen"><div class="arrival-mark">${icon('check')}</div><h1>On the platform</h1><p class="lead">Check the departure board before boarding.</p>${c ? `<div class="panel arrival-info"><strong>${esc(trainName(c))} · ${t(formatTime(c.departureTs))}</strong><p>Platform ${esc(c.platform)} · ${esc(c.connection.to.station.name)}</p></div>` : ''}<p class="muted">This is your own confirmation. Hopp hasn’t verified that you boarded.</p>${fallback(result, true, true)}<div class="bottom-actions">${primary('Plan another trip', 'plan')}</div></section>`;
}
