import type { Candidate, PlanResult } from '../types';
import { formatTime, formatDuration, stopTime } from '../engine';
import { esc, icon, primary, button, safety } from './html';
import { badges, budget, connectionRow, fallback, shortStop, trainName } from './common';
export function resultsScreen(result: PlanResult, dismissed: boolean): string {
  const c = dismissed ? undefined : result.recommended;
  const reason = ({ 'no-shortcut': 'No sprint shortcut on this trip yet. Your regular connections are below.', 'no-connections': 'No connections found. Try a different stop or departure time.', 'no-earlier-train': 'No earlier arrival found for this trip.', 'passed-stop': 'You have passed the shortcut stop. Keep your regular connection.', 'hack-inactive': 'This shortcut is currently unavailable. Follow the regular transfer.', 'missed-by': 'The sprint would not leave enough time for the full margin.', 'candidate-lookup-failed': 'We could not check the sprint route. Use your regular connection.', stale: 'Refresh the timetable before choosing a sprint route.' } as Record<string, string>)[result.reason] ?? result.reason;
  return `<section class="screen results-screen" data-screen="results" data-testid="screen"><div class="trip-title"><p class="eyebrow">${esc(result.connections[0]?.from.station.name ?? result.query.from)} →</p><h1>${esc(result.connections[0]?.to.station.name ?? result.query.to)}</h1></div>
    ${result.error ? `<p class="notice" role="status" data-testid="error">${esc(result.error)}</p>` : ''}
    ${c ? `<article class="offer-card" data-testid="offer-card"><div class="offer-label">${icon('run')} Sprint route available <span class="go-word">GO</span></div><h2>You can still make the <span class="nowrap">${formatTime(c.departureTs)}${icon('arrow')}</span></h2><p>${result.opportunity?.feeder ? 'Get off at' : 'Start at'} <strong>${esc(shortStop(result.opportunity!.hack.alight.name))}</strong>. Take the local shortcut to <strong>Platform ${esc(c.platform)}</strong>.</p>${budget(c)}<p class="offer-spare"><strong>${formatDuration(Math.max(0, c.haveS - c.sprintS - c.marginS))}</strong> spare after margin</p><div class="offer-actions">${primary('Try it', 'try')}${button('Not now', 'dismiss', 'text-button')}</div><p class="offer-footnote">Not yet timed on foot · platform as scheduled</p>${safety}</article>` : `<div class="no-offer"><span class="round-icon">${icon('train')}</span><h2>${result.opportunity?.feeder ? 'Stay aboard.' : 'Your regular connection.'}</h2><p>${esc(dismissed ? 'Your regular connections are below.' : reason || 'No sprint route on this trip yet. Your regular connections are below.')}</p></div>`}
    ${fallback(result, true)}<div class="section-heading"><h2>Regular connections</h2>${button(icon('clock'), 'refresh', 'icon-button', 'aria-label="Refresh connections"')}</div>${result.connections.map(connectionRow).join('')}
    <p class="api-credit">Timetable via transport.opendata.ch · Check tickets with SBB.</p><div class="bottom-actions inline-bottom">${button(`New search ${icon('arrow')}`, 'plan', 'secondary')}</div></section>`;
}
export function tryScreen(result: PlanResult): string {
  const c = result.recommended!;
  return `<section class="screen try-screen" data-screen="try" data-testid="screen"><h1>Sprint details</h1><p class="lead">${esc(trainName(c))} · ${formatTime(c.departureTs)} · Platform ${esc(c.platform)}</p>
    <div class="panel sprint-stats"><div><span>Full sprint</span><strong>${formatDuration(c.sprintS)}</strong></div><div><span>Spare after margin</span><strong class="green">${formatDuration(Math.max(0, c.haveS - c.sprintS - c.marginS))}</strong></div></div>${budget(c)}
    <p class="walking"><span>${icon('run')}</span>${c.walkS + c.marginS <= c.haveS ? 'Walking would also make it.' : `Walking: no. You’d need ${formatDuration(c.walkS)} plus margin.`}</p>
    ${badges(result, c)}${safety}<div class="bottom-actions">${button(`${icon('map')} Show me the route first`, 'route', 'secondary')}${primary('Sprint it', 'detail')}</div></section>`;
}
export function detailScreen(result: PlanResult): string {
  const c = result.recommended!, h = result.opportunity!.hack;
  return `<section class="screen detail-screen" data-screen="detail" data-testid="screen"><p class="eyebrow">Sprint route · ${esc(trainName(c))}</p><h1>You can still<br>make the ${formatTime(c.departureTs)}.</h1>${budget(c)}
    <ol class="timeline"><li><time>${formatTime(result.opportunity!.alightTs)}</time><div><strong>${result.opportunity?.feeder ? 'Get off at' : 'Start at'} ${esc(shortStop(h.alight.name))}</strong><p>${esc(h.alight.platformLetters[result.opportunity?.feeder?.journey?.number ?? ''] ? `Stop ${h.alight.platformLetters[result.opportunity?.feeder?.journey?.number ?? '']}` : 'Use the marked public crossing')}</p></div></li><li><time>${formatDuration(c.sprintS)}</time><div><strong>${Math.round(c.route?.path.reduce((sum, step) => sum + ('m' in step ? step.m : 0), 0) ?? 0)} m sprint</strong><p>${esc(c.route?.label)}</p>${button(`${icon('map')} Preview the route`, 'route', 'text-button')}</div></li><li><time>${formatTime(c.departureTs)}</time><div><strong>${esc(trainName(c))} · Platform ${esc(c.platform)}</strong><p>Arrive ${formatTime(c.arrivalTs)} · ${Math.round(c.gainS / 60)} min before your regular plan</p></div></li></ol>
    ${fallback(result, true)}${badges(result, c)}${safety}<div class="bottom-actions">${primary('Go live', 'live')}</div></section>`;
}
export function doneScreen(result: PlanResult, selected?: Candidate): string {
  const c = selected ?? result.recommended;
  return `<section class="screen done-screen" data-screen="done" data-testid="screen"><div class="arrival-mark">${icon('check')}</div><h1>On the platform</h1><p class="lead">Check the departure board before boarding.</p>${c ? `<div class="panel arrival-info"><strong>${esc(trainName(c))} · ${formatTime(c.departureTs)}</strong><p>Platform ${esc(c.platform)} · ${esc(c.connection.to.station.name)}</p></div>` : ''}<p class="muted">This is your own confirmation. Hopp hasn’t verified that you boarded.</p>${fallback(result, true, true)}<div class="bottom-actions">${primary('Plan another trip', 'plan')}</div></section>`;
}
